// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddNoteReducer from "../add_note_reducer";
import DeleteNoteReducer from "../delete_note_reducer";

export type AddNoteParams = __Infer<typeof AddNoteReducer>;
export type DeleteNoteParams = __Infer<typeof DeleteNoteReducer>;

